name: Validate Build
description: Compare two sets of build artifacts for consistency (architecture, size, functionality)

inputs:
  expected-dir:
    description: 'Directory containing expected/reference binaries'
    required: true
  actual-dir:
    description: 'Directory containing actual/new binaries to validate'
    required: true
  size-tolerance:
    description: 'Maximum allowed size difference as percentage (default: 10)'
    required: false
    default: '10'
  health-check:
    description: 'Command to run for health check (e.g., "version", "--version"). Binary path is prepended automatically.'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - id: validate
      shell: bash
      run: |
        # Convert Windows backslashes to forward slashes for Git Bash compatibility
        ACTION_PATH="${{ github.action_path }}"
        ACTION_PATH="${ACTION_PATH//\\//}"
        "${ACTION_PATH}/validate-build.sh" \
          '${{ inputs.expected-dir }}' \
          '${{ inputs.actual-dir }}' \
          --size-tolerance=${{ inputs.size-tolerance }} \
          --health-check='${{ inputs.health-check }}'
