name: Validate Build
description: Compare two sets of build artifacts for consistency (architecture, size, functionality)

inputs:
  expected-dir:
    description: 'Directory containing expected/reference binaries'
    required: true
  actual-dir:
    description: 'Directory containing actual/new binaries to validate'
    required: true
  size-tolerance:
    description: 'Maximum allowed size difference as percentage (default: 10)'
    required: false
    default: '10'

runs:
  using: composite
  steps:
    - id: validate
      shell: bash
      run: |
        ${{ github.action_path }}/validate-build.sh \
          '${{ inputs.expected-dir }}' \
          '${{ inputs.actual-dir }}' \
          --size-tolerance=${{ inputs.size-tolerance }}
